package neo4j.relations;

public interface Relations {

  String ORGANIZATION_PERSONS = "ORGANIZATION_PERSONS";
  String PERSON_SKILLS = "PERSON_SKILLS";
  String ORGANIZATION_SUB_ORGANIZATION = "ORGANIZATION_SUB_ORGANIZATION";
  String ORGANIZATION_HEAD_OF = "ORGANIZATION_HEAD_OF";
  String PROJECT_MANAGER = "PROJECT_MANAGER";
  String PROJECT_TEAM = "PROJECT_TEAM";
  String PROJECT_ORGANIZATION = "PROJECT_ORGANIZATION";
}
